name: CI

on:
    push:
        branches:
            - main
    pull_request:

# cancel in-progress runs on new commits to same PR (gitub.event.number)
concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
    cancel-in-progress: true

permissions:
    contents: read # to fetch code (actions/checkout)

jobs:
    Lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8.6.3
                  run_install: true
            - run: pnpm run lint

    Check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8.6.3
                  run_install: true
            - run: pnpm run build && pnpm run check

    Tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8.6.3
                  run_install: true
            - run: pnpm run test
